apiVersion: v1
kind: Service
metadata:
  name: helpdesk-backend-service
  namespace: helpdesk
  labels:
    app: helpdesk-backend
spec:
  type: ClusterIP
  selector:
    app: helpdesk-backend
  ports:
    - port: 80
      targetPort: 7860
      protocol: TCP
      name: http