from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Union, Any

class TicketRequest(BaseModel):
    text: str = Field(..., description="The main content or description of the support ticket")
    image_base64: str = Field("", description="Base64 encoded string of an attached image, if any")
    image_text: str = Field("", description="Extracted text from the image for backward compatibility")
    user_id: Optional[str] = Field(None, description="The ID of the user submitting the ticket")
    company: Optional[str] = Field(None, description="Company name associated with the user")
    image_url: Optional[str] = Field(None, description="Public URL to the attached image")
    confidence_threshold: float = Field(0.20, description="Minimum confidence score required for AI categorization")
    duplicate_sensitivity: float = Field(0.85, description="Sensitivity threshold for semantic duplicate detection")

class TicketSaveRequest(BaseModel):
    user_id: str = Field(..., description="The ID of the user owning the ticket")
    subject: str = Field(..., description="Short summary or subject of the ticket")
    description: str = Field(..., description="Full description of the issue")
    category: str = Field(..., description="AI-predicted or user-selected category")
    subcategory: str = Field(..., description="AI-predicted or user-selected subcategory")
    priority: str = Field(..., description="Priority level (e.g., Low, Medium, High, Critical)")
    assigned_team: str = Field(..., description="Team assigned to handle the ticket")
    status: str = Field(..., description="Current status of the ticket (e.g., Open, In Progress)")
    auto_resolve: bool = Field(..., description="Flag indicating if the issue can be auto-resolved")
    is_duplicate: bool = Field(..., description="Flag indicating if this is a duplicate ticket")
    confidence: float = Field(..., description="AI confidence score for the prediction")
    image_url: Optional[str] = Field(None, description="URL of an attached image")
    company: Optional[str] = Field(None, description="User's company name")
    company_id: Optional[str] = Field(None, description="User's company ID")
    sla_breach_at: str = Field(..., description="ISO 8601 timestamp for SLA breach")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context or metadata")
    entities: List[Any] = Field(default_factory=list, description="Extracted named entities from the ticket")
    solution_steps: List[str] = Field(default_factory=list, description="Suggested steps to resolve the issue")
    ocr_text: str = Field("", description="Text extracted via OCR")
    needs_review: bool = Field(False, description="Flag indicating if the ticket requires human review")
    routing_confidence: float = Field(..., description="Confidence score for the assigned team routing")

class DuplicateInfo(BaseModel):
    is_duplicate: bool = Field(..., description="Whether a duplicate was detected")
    duplicate_ticket_id: Optional[str] = Field(None, description="The ID of the duplicated ticket")
    similarity: float = Field(0.0, description="Semantic similarity score to the duplicate")

class EntityInfo(BaseModel):
    text: str = Field(..., description="The matched entity text")
    label: str = Field(..., description="The type/label of the entity (e.g., IP_ADDRESS, ERROR_CODE)")
    confidence: float = Field(..., description="Confidence score of the extraction")

class TicketResponse(BaseModel):
    id: Optional[Union[str, int]] = Field(None, description="Internal database ID")
    ticket_id: Optional[str] = Field(None, description="Public-facing ticket ID")
    summary: str = Field(..., description="Generated summary of the issue")
    category: str = Field(..., description="Predicted category")
    subcategory: str = Field(..., description="Predicted subcategory")
    priority: str = Field(..., description="Predicted priority")
    auto_resolve: bool = Field(..., description="Whether this issue can be instantly resolved")
    assigned_team: str = Field(..., description="The team best suited to handle this")
    entities: List[EntityInfo] = Field(..., description="Extracted technical entities")
    duplicate_ticket: DuplicateInfo = Field(..., description="Duplicate detection results")
    confidence: float = Field(..., description="Overall confidence of the AI prediction")
    needs_review: bool = Field(False, description="Whether human review is requested")
    reasoning: str = Field("", description="AI reasoning behind the classification")
    decision_factors: List[str] = Field(default_factory=list, description="Key factors influencing the AI decision")
    image_description: str = Field("", description="AI description of the attached image")
    ocr_text: str = Field("", description="Text extracted from the image via OCR")
    image_url: Optional[str] = Field(None, description="URL of the uploaded image")
    highlights: List[str] = Field(default_factory=list, description="Highlighted keywords from the text")
    timeline: Dict[str, Any] = Field(default_factory=dict, description="Audit timeline of analysis steps")
    env_metadata: Dict[str, Any] = Field(default_factory=dict, description="Client environment metadata")
    sla_breach_at: Optional[str] = Field(None, description="ISO 8601 SLA expiration timestamp")
    version: str = Field("2.1.0-Neural-Diagnostic", description="Version of the AI model used")

class Message(BaseModel):
    sender: str = Field(..., description="Sender ID or name")
    message: str = Field(..., description="Message content")
    timestamp: str = Field(..., description="ISO 8601 timestamp")

class TicketRecord(BaseModel):
    ticket_id: str = Field(..., description="Public ticket ID")
    owner_id: str = Field(..., description="ID of the user who created the ticket")
    summary: str = Field(..., description="Ticket subject/summary")
    category: str = Field(..., description="Ticket category")
    subcategory: str = Field(..., description="Ticket subcategory")
    priority: str = Field(..., description="Ticket priority")
    status: str = Field(..., description="Current status")
    assigned_team: str = Field(..., description="Assigned support team")
    created_at: str = Field(..., description="Creation timestamp")
    updated_at: Optional[str] = Field(None, description="Last update timestamp")
    last_user_viewed_at: Optional[str] = Field(None, description="Timestamp when the user last viewed it")
    messages: List[Message] = Field(default_factory=list, description="Chat messages for the ticket")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context")
    timeline: Dict[str, Any] = Field(default_factory=dict, description="Milestones timeline")
